#include "FireworkController.h"

bool FireworkController::Init()
{
	Anim = make_shared<FireworkAnim>();
	Anim->Init();
	AnimState = NONE;

	return true;
}

void FireworkController::Update()
{
	switch (AnimState) {
	case NONE:
		break;

	case EFFECT_S:
		Anim->Play("Firework");
		break;

	default:
		break;
	}
}

void FireworkAnim::Init()
{
	const float EF_KeyFrame = 1200.0f / 50.0f;
	///*	ゴールエフェクト	*/
	::AnimationTable set_Firework;
	set_Firework.SetKind(KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1,
		KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1,
		KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1,
		KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1,
		KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1, KIND::ANIMATION_1,
		KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2,
		KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2,
		KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2,
		KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2,
		KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, KIND::ANIMATION_2, ANIMATION_FINISH);
	set_Firework.SetFrame(FIREWORK_ANIM::ANIM_1, FIREWORK_ANIM::ANIM_2, FIREWORK_ANIM::ANIM_3, FIREWORK_ANIM::ANIM_4, FIREWORK_ANIM::ANIM_5,
		FIREWORK_ANIM::ANIM_6, FIREWORK_ANIM::ANIM_7, FIREWORK_ANIM::ANIM_8, FIREWORK_ANIM::ANIM_9, FIREWORK_ANIM::ANIM_10,
		FIREWORK_ANIM::ANIM_11, FIREWORK_ANIM::ANIM_12, FIREWORK_ANIM::ANIM_13, FIREWORK_ANIM::ANIM_14, FIREWORK_ANIM::ANIM_15,
		FIREWORK_ANIM::ANIM_16, FIREWORK_ANIM::ANIM_17, FIREWORK_ANIM::ANIM_18, FIREWORK_ANIM::ANIM_19, FIREWORK_ANIM::ANIM_20,
		FIREWORK_ANIM::ANIM_21, FIREWORK_ANIM::ANIM_22, FIREWORK_ANIM::ANIM_23, FIREWORK_ANIM::ANIM_24, FIREWORK_ANIM::ANIM_25,
		FIREWORK_ANIM::ANIM_1, FIREWORK_ANIM::ANIM_2, FIREWORK_ANIM::ANIM_3, FIREWORK_ANIM::ANIM_4, FIREWORK_ANIM::ANIM_5,
		FIREWORK_ANIM::ANIM_6, FIREWORK_ANIM::ANIM_7, FIREWORK_ANIM::ANIM_8, FIREWORK_ANIM::ANIM_9, FIREWORK_ANIM::ANIM_10,
		FIREWORK_ANIM::ANIM_11, FIREWORK_ANIM::ANIM_12, FIREWORK_ANIM::ANIM_13, FIREWORK_ANIM::ANIM_14, FIREWORK_ANIM::ANIM_15,
		FIREWORK_ANIM::ANIM_16, FIREWORK_ANIM::ANIM_17, FIREWORK_ANIM::ANIM_18, FIREWORK_ANIM::ANIM_19, FIREWORK_ANIM::ANIM_20,
		FIREWORK_ANIM::ANIM_21, FIREWORK_ANIM::ANIM_22, FIREWORK_ANIM::ANIM_23, FIREWORK_ANIM::ANIM_24, FIREWORK_ANIM::ANIM_25, FIREWORK_ANIM::ANIM_25, ANIMATION_FINISH);
	set_Firework.m_Key = { EF_KeyFrame * 0.0f, EF_KeyFrame * 1.0f, EF_KeyFrame * 2.0f, EF_KeyFrame * 3.0f, EF_KeyFrame * 4.0f,
		EF_KeyFrame * 5.0f, EF_KeyFrame * 6.0f, EF_KeyFrame * 7.0f, EF_KeyFrame * 8.0f, EF_KeyFrame * 9.0f,
		EF_KeyFrame * 10.0f, EF_KeyFrame * 11.0f, EF_KeyFrame * 12.0f, EF_KeyFrame * 13.0f, EF_KeyFrame * 14.0f,
		EF_KeyFrame * 15.0f, EF_KeyFrame * 16.0f, EF_KeyFrame * 17.0f, EF_KeyFrame * 18.0f, EF_KeyFrame * 19.0f,
		EF_KeyFrame * 20.0f, EF_KeyFrame * 21.0f, EF_KeyFrame * 22.0f, EF_KeyFrame * 23.0f, EF_KeyFrame * 24.0f,
		EF_KeyFrame * 25.0f, EF_KeyFrame * 26.0f, EF_KeyFrame * 27.0f, EF_KeyFrame * 28.0f, EF_KeyFrame * 29.0f,
		EF_KeyFrame * 30.0f, EF_KeyFrame * 31.0f, EF_KeyFrame * 32.0f, EF_KeyFrame * 33.0f, EF_KeyFrame * 34.0f,
		EF_KeyFrame * 35.0f, EF_KeyFrame * 36.0f, EF_KeyFrame * 37.0f, EF_KeyFrame * 38.0f, EF_KeyFrame * 39.0f,
		EF_KeyFrame * 40.0f, EF_KeyFrame * 41.0f, EF_KeyFrame * 42.0f, EF_KeyFrame * 43.0f, EF_KeyFrame * 44.0f,
		EF_KeyFrame * 45.0f, EF_KeyFrame * 46.0f, EF_KeyFrame * 47.0f, EF_KeyFrame * 48.0f, EF_KeyFrame * 49.0f, 3000.0f };
	AnimationTableList.insert(std::make_pair("Firework", set_Firework));

	/*	表示テクスチャ初期化	*/
	m_animationFrame = 0;
	m_kind = 0;

	/*	最大数設定	*/
	KindMax = KIND::KIND_MAX;
	FrameMax = FIREWORK_ANIM::ANIM_MAX;
}
